-- =============================================================
-- INSTRUCCION · calibrar MODELO = gpt-5-nano (13 tipos PROMPT_<TIPO>)
-- TK-1431662 · Respuesta final por tipo de consulta
-- Compatible con /api/patyia/db/exec (sin GO)
-- =============================================================

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

UPDATE i
SET i.[MODELO] = N'gpt-5-nano'
FROM dbo.INSTRUCCION i
WHERE i.[IINSTRUCCION] IN (
	N'SALUDO_OTRO',
	N'FUERA_DE_ALCANCE_TECNICO',
	N'SOLICITUD_NO_PERMITIDA',
	N'REQUIERE_CONTEXTO',
	N'PASO_A_PASO',
	N'INTERPRETACION_RESULTADO',
	N'CONSULTA_NORMATIVA_NEGOCIO',
	N'ASESORIA_PERSONALIZADA',
	N'ERROR_TECNICO',
	N'ERROR_CONFIGURACION',
	N'ERROR_ACCESO',
	N'ERROR_DIAN',
	N'COMERCIAL'
);

COMMIT;

SELECT
	i.[IINSTRUCCION],
	i.[NINSTRUCCION],
	i.[MODELO],
	i.[VERSION],
	i.[BACTIVO]
FROM dbo.INSTRUCCION i
WHERE i.[IINSTRUCCION] IN (
	N'SALUDO_OTRO',
	N'FUERA_DE_ALCANCE_TECNICO',
	N'SOLICITUD_NO_PERMITIDA',
	N'REQUIERE_CONTEXTO',
	N'PASO_A_PASO',
	N'INTERPRETACION_RESULTADO',
	N'CONSULTA_NORMATIVA_NEGOCIO',
	N'ASESORIA_PERSONALIZADA',
	N'ERROR_TECNICO',
	N'ERROR_CONFIGURACION',
	N'ERROR_ACCESO',
	N'ERROR_DIAN',
	N'COMERCIAL'
)
ORDER BY i.[IINSTRUCCION];
