USE CLIENTES;

-- ============================================================================
-- ELIMINAR INDICES
-- ============================================================================

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_BACTIVO' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_PLANES_ESTUDIO_BACTIVO ON CAPAC_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_FHCRE' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_PLANES_ESTUDIO_FHCRE ON CAPAC_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_PLANES_ESTUDIO_IUSUARIOCRE ON CAPAC_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_TTDVISUALIZACION' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_PLANES_ESTUDIO_TTDVISUALIZACION ON CAPAC_PLANES_ESTUDIO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_BACTIVO' AND object_id = OBJECT_ID('CAPAC_CURSOS')) DROP INDEX IX_CAPAC_CURSOS_BACTIVO ON CAPAC_CURSOS;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_FHCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS')) DROP INDEX IX_CAPAC_CURSOS_FHCRE ON CAPAC_CURSOS;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS')) DROP INDEX IX_CAPAC_CURSOS_IUSUARIOCRE ON CAPAC_CURSOS;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_IDRIVER' AND object_id = OBJECT_ID('CAPAC_CURSOS')) DROP INDEX IX_CAPAC_CURSOS_IDRIVER ON CAPAC_CURSOS;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IPLANESTUDIO' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IPLANESTUDIO ON CAPAC_CURSOS_DE_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_ICURSO' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_ICURSO ON CAPAC_CURSOS_DE_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_FHCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_FHCRE ON CAPAC_CURSOS_DE_PLANES_ESTUDIO;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO')) DROP INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IUSUARIOCRE ON CAPAC_CURSOS_DE_PLANES_ESTUDIO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_ICURSO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS')) DROP INDEX IX_CAPAC_CURSOS_PREREQUISITOS_ICURSO ON CAPAC_CURSOS_PREREQUISITOS;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_ICURSOREQUERIDO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS')) DROP INDEX IX_CAPAC_CURSOS_PREREQUISITOS_ICURSOREQUERIDO ON CAPAC_CURSOS_PREREQUISITOS;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_IPLANESTUDIO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS')) DROP INDEX IX_CAPAC_CURSOS_PREREQUISITOS_IPLANESTUDIO ON CAPAC_CURSOS_PREREQUISITOS;

-- ============================================================================
-- ELIMINAR TABLAS
-- ============================================================================

-- Eliminar tablas con FK primero (orden inverso de dependencias)
IF OBJECT_ID('CAPAC_HISTORIALPLANESTUDIO', 'U') IS NOT NULL DROP TABLE CAPAC_HISTORIALPLANESTUDIO;
IF OBJECT_ID('CAPAC_HISTORIALCURSO', 'U') IS NOT NULL DROP TABLE CAPAC_HISTORIALCURSO;
IF OBJECT_ID('CAPAC_ESTRUCTURAS_CURSOS', 'U') IS NOT NULL DROP TABLE CAPAC_ESTRUCTURAS_CURSOS;
IF OBJECT_ID('CAPAC_ATRIBUTOS_PLANES', 'U') IS NOT NULL DROP TABLE CAPAC_ATRIBUTOS_PLANES;
IF OBJECT_ID('CAPAC_PLANES_CURSOS', 'U') IS NOT NULL DROP TABLE CAPAC_PLANES_CURSOS;
IF OBJECT_ID('CAPAC_SEGURIDADES_CURSOS', 'U') IS NOT NULL DROP TABLE CAPAC_SEGURIDADES_CURSOS;
IF OBJECT_ID('CAPAC_ATRIBUTOS_X_DRIVERS', 'U') IS NOT NULL DROP TABLE CAPAC_ATRIBUTOS_X_DRIVERS;
IF OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS', 'U') IS NOT NULL DROP TABLE CAPAC_CURSOS_PREREQUISITOS;
IF OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO', 'U') IS NOT NULL DROP TABLE CAPAC_CURSOS_DE_PLANES_ESTUDIO;
-- Eliminar tablas base
IF OBJECT_ID('CAPAC_CURSOS', 'U') IS NOT NULL DROP TABLE CAPAC_CURSOS;
IF OBJECT_ID('CAPAC_PLANES_ESTUDIO', 'U') IS NOT NULL DROP TABLE CAPAC_PLANES_ESTUDIO;
IF OBJECT_ID('CAPAC_DRIVERS', 'U') IS NOT NULL DROP TABLE CAPAC_DRIVERS;
IF OBJECT_ID('PERMISOS', 'U') IS NOT NULL DROP TABLE PERMISOS;
IF OBJECT_ID('CAPAC_TEMAS', 'U') IS NOT NULL DROP TABLE CAPAC_TEMAS;

-- ============================================================================
-- ELIMINAR SECUENCIAS
-- ============================================================================

IF OBJECT_ID('CAPAC_SEQ_IHISTORIALPLANESTUDIO', 'SO') IS NOT NULL DROP SEQUENCE CAPAC_SEQ_IHISTORIALPLANESTUDIO;
IF OBJECT_ID('CAPAC_SEQ_IHISTORIALCURSO', 'SO') IS NOT NULL DROP SEQUENCE CAPAC_SEQ_IHISTORIALCURSO;
IF OBJECT_ID('CAPAC_SEQ_IDRIVER', 'SO') IS NOT NULL DROP SEQUENCE CAPAC_SEQ_IDRIVER;
IF OBJECT_ID('CAPAC_SEQ_IRECURSO', 'SO') IS NOT NULL DROP SEQUENCE CAPAC_SEQ_IRECURSO;
IF OBJECT_ID('CAPAC_SEQ_IATRIBUTOXTDRECURSO', 'SO') IS NOT NULL DROP SEQUENCE CAPAC_SEQ_IATRIBUTOXTDRECURSO;

-- ============================================================================
-- SECUENCIAS PARA GENERACIÃ“N DE IDS (CON PREFIJO CAPAC_)
-- ============================================================================

IF OBJECT_ID('CAPAC_SEQ_IHISTORIALPLANESTUDIO', 'SO') IS NULL
CREATE SEQUENCE CAPAC_SEQ_IHISTORIALPLANESTUDIO START WITH 1 INCREMENT BY 1;

IF OBJECT_ID('CAPAC_SEQ_IHISTORIALCURSO', 'SO') IS NULL
CREATE SEQUENCE CAPAC_SEQ_IHISTORIALCURSO START WITH 1 INCREMENT BY 1;

IF OBJECT_ID('CAPAC_SEQ_IDRIVER', 'SO') IS NULL
CREATE SEQUENCE CAPAC_SEQ_IDRIVER START WITH 1 INCREMENT BY 1;

IF OBJECT_ID('CAPAC_SEQ_IRECURSO', 'SO') IS NULL
CREATE SEQUENCE CAPAC_SEQ_IRECURSO START WITH 1 INCREMENT BY 1;

IF OBJECT_ID('CAPAC_SEQ_IATRIBUTOXTDRECURSO', 'SO') IS NULL
CREATE SEQUENCE CAPAC_SEQ_IATRIBUTOXTDRECURSO START WITH 1 INCREMENT BY 1;

-- ============================================================================
-- TABLAS PRINCIPALES (CON PREFIJO CAPAC_)
-- ============================================================================

-- Tabla CAPAC_DRIVERS
IF OBJECT_ID('CAPAC_DRIVERS', 'U') IS NULL
CREATE TABLE CAPAC_DRIVERS (
    IDRIVER BIGINT PRIMARY KEY,
    NDRIVER VARCHAR(255),
    DESCRIPCION TEXT,
    QNIVELES TINYINT,
    IAPPCRE VARCHAR(255),
    IUSUARIOCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE()
);

-- Tabla CAPAC_PLANES_ESTUDIO
IF OBJECT_ID('CAPAC_PLANES_ESTUDIO', 'U') IS NULL
CREATE TABLE CAPAC_PLANES_ESTUDIO (
    IPLANESTUDIO VARCHAR(255) PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DESCRIPCIONPLAN TEXT,
    TTDVISUALIZACION VARCHAR(50),
    BACTIVO BIT DEFAULT 1,
    BGENERACERTIFICADOS BIT DEFAULT 0,
    IRECURSO VARCHAR(255) NULL,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE()
);

-- Tabla CAPAC_TEMAS
IF OBJECT_ID('CAPAC_TEMAS', 'U') IS NULL
CREATE TABLE CAPAC_TEMAS (
    ITEMA VARCHAR(255) PRIMARY KEY,
    NTEMA VARCHAR(255),
    IUSUARIOCRE VARCHAR(255) NULL,
    IAPPCRE VARCHAR(255) NULL,
    IPCRE VARCHAR(255) NULL,
    FHCRE DATETIME2(7) NULL DEFAULT (GETDATE()),
    IUSUARIOULT VARCHAR(255) NULL,
    IAPPULT VARCHAR(255) NULL,
    IPULT VARCHAR(255) NULL,
    FHULT DATETIME2(7) NULL DEFAULT (GETDATE())
);

-- Tabla CAPAC_CURSOS
IF OBJECT_ID('CAPAC_CURSOS', 'U') IS NULL
CREATE TABLE CAPAC_CURSOS (
    ICURSO VARCHAR(255) PRIMARY KEY,
    NCURSO VARCHAR(255),
    ITEMA VARCHAR(255),
    DESCRIPCION TEXT,
    IDRIVER BIGINT,
    BACTIVO BIT DEFAULT 1,
    BGENERACERTIFICADO BIT DEFAULT 0,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE()
);

-- Tabla PERMISOS
IF OBJECT_ID('PERMISOS', 'U') IS NULL
CREATE TABLE PERMISOS (
    IPERMISO VARCHAR(255) PRIMARY KEY,
    NPERMISO VARCHAR(255)
);

-- ============================================================================
-- TABLAS PIVOTE Y DETALLES
-- ============================================================================

-- Tabla CAPAC_CURSOS_DE_PLANES_ESTUDIO
IF OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO', 'U') IS NULL
CREATE TABLE CAPAC_CURSOS_DE_PLANES_ESTUDIO (
    IPLANESTUDIO VARCHAR(255),
    ICURSO VARCHAR(255),
    QORDEN INT,
    BREQUERIDO BIT DEFAULT 1,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (IPLANESTUDIO, ICURSO)
);

-- Tabla CAPAC_CURSOS_PREREQUISITOS
IF OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS', 'U') IS NULL
CREATE TABLE CAPAC_CURSOS_PREREQUISITOS (
    ICURSO VARCHAR(255),
    ICURSOREQUERIDO VARCHAR(255),
    IPLANESTUDIO VARCHAR(255),
    PRIMARY KEY (ICURSO, ICURSOREQUERIDO, IPLANESTUDIO)
);

-- Tabla CAPAC_ATRIBUTOS_X_DRIVERS
IF OBJECT_ID('CAPAC_ATRIBUTOS_X_DRIVERS', 'U') IS NULL
CREATE TABLE CAPAC_ATRIBUTOS_X_DRIVERS (
    IDRIVER BIGINT,
    IATRIBUTO BIGINT,
    QNIVEL TINYINT,
    NATRIBUTO VARCHAR(255),
    BREQUERIDO BIT DEFAULT 0,
    JCONFIG VARCHAR(MAX),
    /* Etiqueta legible para formularios (no codigo interno) */ TDATRIBUTO TINYINT DEFAULT 0,
    PRIMARY KEY (IDRIVER, IATRIBUTO)
);

-- Tabla CAPAC_SEGURIDADES_CURSOS
IF OBJECT_ID('CAPAC_SEGURIDADES_CURSOS', 'U') IS NULL
CREATE TABLE CAPAC_SEGURIDADES_CURSOS (
    ICURSO VARCHAR(255),
    IPERMISO VARCHAR(255),
    BACTIVO BIT DEFAULT 1,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (ICURSO, IPERMISO)
);

-- Tabla CAPAC_PLANES_CURSOS
IF OBJECT_ID('CAPAC_PLANES_CURSOS', 'U') IS NULL
CREATE TABLE CAPAC_PLANES_CURSOS (
    IPLAN VARCHAR(255),
    ICURSO VARCHAR(255),
    TITULO VARCHAR(255),
    ITEMA VARCHAR(25),
    IRECURSO VARCHAR(255),
    IPLANPADRE VARCHAR(255),
    BACTIVO BIT DEFAULT 1,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (IPLAN, ICURSO)
);

-- Tabla CAPAC_ATRIBUTOS_PLANES
IF OBJECT_ID('CAPAC_ATRIBUTOS_PLANES', 'U') IS NULL
CREATE TABLE CAPAC_ATRIBUTOS_PLANES (
    IPLAN VARCHAR(255),
    ICURSO VARCHAR(255),
    IATRIBUTO BIGINT,
    BACTIVO BIT DEFAULT 1,
    VALOR VARCHAR(MAX),
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (IPLAN, ICURSO, IATRIBUTO)
);

-- Tabla CAPAC_ESTRUCTURAS_CURSOS
IF OBJECT_ID('CAPAC_ESTRUCTURAS_CURSOS', 'U') IS NULL
CREATE TABLE CAPAC_ESTRUCTURAS_CURSOS (
    ICURSO VARCHAR(255),
    QNIVEL TINYINT,
    NNIVEL VARCHAR(255),
    BACTIVO BIT DEFAULT 1,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2 DEFAULT GETDATE(),
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (ICURSO, QNIVEL)
);

-- ============================================================================
-- TABLAS DE HISTORIAL (AUDITORÃA)
-- ============================================================================

IF OBJECT_ID('CAPAC_HISTORIALPLANESTUDIO', 'U') IS NULL
CREATE TABLE CAPAC_HISTORIALPLANESTUDIO (
    IHISTORIALPLANESTUDIO BIGINT PRIMARY KEY,
    IPLANESTUDIO VARCHAR(255),
    CAMPO VARCHAR(255),
    VALOR TEXT,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2,
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2
);

IF OBJECT_ID('CAPAC_HISTORIALCURSO', 'U') IS NULL
CREATE TABLE CAPAC_HISTORIALCURSO (
    IHISTORIALCURSO BIGINT PRIMARY KEY,
    ICURSO VARCHAR(255),
    CAMPO VARCHAR(255),
    VALOR TEXT,
    IUSUARIOCRE VARCHAR(255),
    IAPPCRE VARCHAR(255),
    IPCRE VARCHAR(255),
    FHCRE DATETIME2,
    IUSUARIOULT VARCHAR(255),
    IAPPULT VARCHAR(255),
    IPULT VARCHAR(255),
    FHULT DATETIME2
);

-- ============================================================================
-- ÃNDICES (CON PREFIJO CAPAC_)
-- ============================================================================

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_BACTIVO' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_PLANES_ESTUDIO_BACTIVO ON CAPAC_PLANES_ESTUDIO(BACTIVO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_FHCRE' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_PLANES_ESTUDIO_FHCRE ON CAPAC_PLANES_ESTUDIO(FHCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_PLANES_ESTUDIO_IUSUARIOCRE ON CAPAC_PLANES_ESTUDIO(IUSUARIOCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_PLANES_ESTUDIO_TTDVISUALIZACION' AND object_id = OBJECT_ID('CAPAC_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_PLANES_ESTUDIO_TTDVISUALIZACION ON CAPAC_PLANES_ESTUDIO(TTDVISUALIZACION);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_BACTIVO' AND object_id = OBJECT_ID('CAPAC_CURSOS'))
CREATE INDEX IX_CAPAC_CURSOS_BACTIVO ON CAPAC_CURSOS(BACTIVO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_FHCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS'))
CREATE INDEX IX_CAPAC_CURSOS_FHCRE ON CAPAC_CURSOS(FHCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS'))
CREATE INDEX IX_CAPAC_CURSOS_IUSUARIOCRE ON CAPAC_CURSOS(IUSUARIOCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_IDRIVER' AND object_id = OBJECT_ID('CAPAC_CURSOS'))
CREATE INDEX IX_CAPAC_CURSOS_IDRIVER ON CAPAC_CURSOS(IDRIVER);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IPLANESTUDIO' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IPLANESTUDIO ON CAPAC_CURSOS_DE_PLANES_ESTUDIO(IPLANESTUDIO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_ICURSO' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_ICURSO ON CAPAC_CURSOS_DE_PLANES_ESTUDIO(ICURSO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_FHCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_FHCRE ON CAPAC_CURSOS_DE_PLANES_ESTUDIO(FHCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IUSUARIOCRE' AND object_id = OBJECT_ID('CAPAC_CURSOS_DE_PLANES_ESTUDIO'))
CREATE INDEX IX_CAPAC_CURSOS_DE_PLANES_ESTUDIO_IUSUARIOCRE ON CAPAC_CURSOS_DE_PLANES_ESTUDIO(IUSUARIOCRE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_ICURSO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS'))
CREATE INDEX IX_CAPAC_CURSOS_PREREQUISITOS_ICURSO ON CAPAC_CURSOS_PREREQUISITOS(ICURSO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_ICURSOREQUERIDO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS'))
CREATE INDEX IX_CAPAC_CURSOS_PREREQUISITOS_ICURSOREQUERIDO ON CAPAC_CURSOS_PREREQUISITOS(ICURSOREQUERIDO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAPAC_CURSOS_PREREQUISITOS_IPLANESTUDIO' AND object_id = OBJECT_ID('CAPAC_CURSOS_PREREQUISITOS'))
CREATE INDEX IX_CAPAC_CURSOS_PREREQUISITOS_IPLANESTUDIO ON CAPAC_CURSOS_PREREQUISITOS(IPLANESTUDIO);
