/** DDL CONVERSACION_LOG (staging) — TK-1432903. */
export const SQL_CONVERSACION_LOG_DDL = `SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.CONVERSACION_LOG', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[CONVERSACION_LOG] (
		[ICONVERSACION] BIGINT NOT NULL,
		[CONTENT]       NVARCHAR(MAX) NOT NULL
	);
END;`;
