-- CONVERSACION_LOG · DDL (AYUDASCP_IA producción)

USE [AYUDASCP_IA];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.CONVERSACION_LOG', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[CONVERSACION_LOG] (
		[ICONVERSACION] BIGINT NOT NULL,
		[CONTENT]       NVARCHAR(MAX) NOT NULL
	);
END;
GO
